import Head from 'next/head';
import { SignInButton, useUser } from '@clerk/nextjs';
import {
  Box,
  Heading,
} from '@chakra-ui/react';
import ParentWrapper from './components/parentWrapper';

export default function Home() {
  const { isSignedIn } = useUser();

  return (
    <>
      <Head>
        <title>BlockChit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ParentWrapper>
          <Box
            flexDirection={'row'}
            alignSelf={'center'}
            justifyContent={'space-between'}
            alignContent={'center'}
          >
            <Box alignItems={'center'}>
              <Box>
                <Heading
                  mb="8"
                  fontWeight="extrabold"
                  size="2xl"
                  bgGradient="linear(to-r, orange.500, orange.300, pink.500)"
                  bgClip="text"
                >
                  Project Name
                </Heading>
              </Box>
              {!isSignedIn && (
                <SignInButton mode="modal" redirectUrl="/screens/walletConnect">
                  <Box bg="orange.600" padding={5} alignContent={'ce'}>
                    Sign In
                  </Box>
                </SignInButton>
              )}
            </Box>
          </Box>
        </ParentWrapper>
      </main>
    </>
  );
}
