import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { SignInButton, useUser, UserButton } from '@clerk/nextjs';

export default function Home() {
  const { isSignedIn } = useUser();

  return (
    <>
      <Head>
        <title>BlockChit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {!isSignedIn && <SignInButton mode="modal" redirectUrl='/screens/walletConnect'/>}
        <UserButton/>
      </main>
    </>
  );
}
